name: iOL Digital
favicon: null
layout_spectrum: 0.2107
typography_spectrum: 0.76421
title: iOL Digital Marketing Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ccccce'
    - '#5d5061'
    - '#0101bb'
    - '#d8a001'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 1
purpose: []
