name: iOL Digital
favicon: null
layout_spectrum: 0.7191134144086391
typography_spectrum: 0.5999734057113528
title: iOL Digital Marketing Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.48253185977227986
  lightness: 0.15728198271244764
  saturation: 0.7530247392132878
  rhythmicContrast: 0.016230529407039285
purpose: []
